version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=shopper
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "3306:3306"