version: "3"

networks:
  my-network:

services:
  mysql:
    image: mysql
    container_name: shopper_mysql
    environment:
      - MYSQL_DATABASE=shopper
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin123
    networks:
      - my-network
    ports:
      - "3306:3306"

  app:
    build: ./frontend/
    container_name: shopper_app
    ports:
      - "5173:5173"
    networks:
      - my-network

  api:
    build: ./backend/
    container_name: shopper_api
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - my-network
